# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f60687d27edad1097fba27206171369c25a5656067029aabce9b45e170492d5e964dd2de77dc79c9b14acc73f3bf897c3116d600d13c5af2d185643ecb0200b7

test:
  secret_key_base: ae7cf774209c59018e64c4416d62e15da6b5c3de3510609d288d5c569aa01777e39675b9fdad045b15a4e78dda235f19f6ba03411363c79b0d3376ebcbf18857

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
